# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

import_from_git(
  url: "git@git.chinawayltd.com:ios/common/Fastfiles.git", # The URL of the repository to import the Fastfile from.
  branch: "master", # The branch to checkout on the repository. Defaults to `HEAD`.
  path: "fastlane/ios_fastfile.rb" # The path of the Fastfile in the repository. Defaults to `fastlane/Fastfile`.
  # version: "~> 1.0.0" #The version to checkout on the respository. Optimistic operator can be used to select the latest version within constraints.
)

platform :ios do
  desc "Verify"
  lane :verify do |options|
    verify_component(
      project:"G7_Component"
    )
  end
end

platform :ios do
  desc "发布组件"
  lane :deploy do
    deploy_component(
      branch:"master",
      project:"G7_Component"
    )
  end
end